final List<String> concepts = [
  'Rebase en la calle izquierda, no en la derecha.',
  'Prohibido estacionarse en banquetas rojas.',
  'En cruceros, no avanzar si no hay espacio en la siguiente cuadra.',
  'Al dar vuelta a la izquierda, usar el carril extremo izquierdo.',
  'En glorietas sin semáforos, prioridad a los que ya están en circulación.',
  'Prohibido detenerse en doble fila.',
  'Rebasar desde el carril derecho solo si hay más de dos carriles en el mismo sentido.',
  'Señal de alto requiere un alto total.',
  'Señalamientos de velocidad en Tijuana están en kilómetros por hora.',
  'Indicación de oficial de tránsito con la mano derecha es preventiva.',
  'Prohibido para ciclistas desplazarse en estado de ebriedad.',
  'Señal de vuelta en U no permitida.',
  'No rebasar si la línea discontinua no está de tu lado.',
  'Señal de advertencia indica vialidad dividida.',
  'Señal de precaución con fauna silvestre.',
  'En caminos con tres o más carriles, el carril izquierdo es para rebasar vehículos más lentos.',
  'Número de personas en el vehículo según la tarjeta de circulación.',
  'En caso de accidente, permanecer en el lugar y verificar el estado de los ocupantes.',
  'Preferencia de vía para calles pavimentadas.',
];
